'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace SideBySideBar2DChart.Properties

    ''' <summary>
    '''   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    ''' </summary>
    ' Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    ' -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    ' Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    ' mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(SideBySideBar2DChart.Properties.Resources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(SideBySideBar2DChart.Properties.Resources).Assembly)
                    SideBySideBar2DChart.Properties.Resources.resourceMan = temp
                End If

                Return SideBySideBar2DChart.Properties.Resources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return SideBySideBar2DChart.Properties.Resources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                SideBySideBar2DChart.Properties.Resources.resourceCulture = value
            End Set
        End Property
    End Class
End Namespace
