'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace SideBySideBar2DChart.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As SideBySideBar2DChart.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New SideBySideBar2DChart.Properties.Settings())), SideBySideBar2DChart.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return SideBySideBar2DChart.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
